/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Thu Nov 26 11:31:31 2015
 * --------------------------------------------------------
 *
 */
#ifndef USER_ALL_ID_h
#define USER_ALL_ID_h

// ============================================================ //


// joint

#define FJ_T1_Coman_id 1
#define FJ_T2_Coman_id 2
#define FJ_T3_Coman_id 3
#define FJ_R1_Coman_id 4
#define FJ_R2_Coman_id 5
#define FJ_R3_Coman_id 6
#define RHipSag_id 7
#define RHipLat_id 8
#define RHipYaw_id 9
#define RKneeSag_id 10
#define RAnkLat_id 11
#define RAnkSag_id 12
#define LHipSag_id 13
#define LHipLat_id 14
#define LHipYaw_id 15
#define LKneeSag_id 16
#define LAnkLat_id 17
#define LAnkSag_id 18
#define WaistLat_id 19
#define WaistSag_id 20
#define WaistYaw_id 21
#define RShSag_id 22
#define RShLat_id 23
#define RShYaw_id 24
#define RElb_id 25
#define LShSag_id 26
#define LShLat_id 27
#define LShYaw_id 28
#define LElb_id 29


// body

#define Waist_id 6
#define RHipmot_id 7
#define RThighUpLeg_id 8
#define RThighLowLeg_id 9
#define RLowLeg_id 10
#define RFootmot_id 11
#define RFoot_id 12
#define LHipmot_id 13
#define LThighUpLeg_id 14
#define LThighLowLeg_id 15
#define LLowLeg_id 16
#define LFootmot_id 17
#define LFoot_id 18
#define DWL_id 19
#define DWS_id 20
#define DWYTorso_id 21
#define RShp_id 22
#define RShr_id 23
#define RShy_id 24
#define RElb_id 25
#define LShp_id 26
#define LShr_id 27
#define LShy_id 28
#define LElb_id 29


// point

//#define origin_id 0
#define Point_Waist_1_id 1
#define Point_Waist_2_id 2
#define Point_Waist_3_id 3
#define Point_Waist_Cg_id 4
#define Point_RHipmot_id 5
#define Point_RHipmot_Cg_id 6
#define Point_RThighUpLeg_id 7
#define Point_RThighUpLeg_Cg_id 8
//#define origin_id 9
#define Point_RThighLowLeg_id 10
#define Point_RThighLowLeg_Cg_id 11
//#define origin_id 12
#define Point_RLowLeg_id 13
#define Point_RLowLeg_Cg_id 14
#define Point_RFootmot_id 15
#define Point_RFootmot_Cg_id 16
#define Point_RFoot_Cg_id 17
#define Point_RFoot_F_id 18
#define Point_LHipmot_id 19
#define Point_LHipmot_Cg_id 20
#define Point_LThighUpLeg_id 21
#define Point_LThighUpLeg_Cg_id 22
//#define origin_id 23
#define Point_LThighLowLeg_id 24
#define Point_LThighLowLeg_Cg_id 25
//#define origin_id 26
#define Point_LLowLeg_id 27
#define Point_LLowLeg_Cg_id 28
#define Point_LFootmot_id 29
#define Point_LFootmot_Cg_id 30
#define Point_LFoot_Cg_id 31
#define Point_LFoot_F_id 32
#define Point_DWL_id 33
#define Point_DWL_Cg_id 34
#define Point_DWS_id 35
#define Point_DWS_Cg_id 36
//#define origin_id 37
#define Point_DWYTorso_Cg_id 38
#define Point_DWYTorso_1_id 39
#define Point_DWYTorso_2_id 40
#define Point_RShp_Cg_id 41
#define Point_RShp_id 42
#define Point_RShr_Cg_id 43
#define Point_RShr_id 44
//#define origin_id 45
#define Point_RShy_Cg_id 46
#define Point_RShy_id 47
//#define origin_id 48
#define Point_RElb_Cg_id 49
#define Point_LShp_Cg_id 50
#define Point_LShp_id 51
#define Point_LShr_Cg_id 52
#define Point_LShr_id 53
//#define origin_id 54
#define Point_LShy_Cg_id 55
#define Point_LShy_id 56
//#define origin_id 57
#define Point_LElb_Cg_id 58


// sensor

#define WaistCg_id 1
#define RHipmotCg_id 2
#define RThighUpLegCg_id 3
#define RThighLowLegCg_id 4
#define RLowLegCg_id 5
#define RFootmotCg_id 6
#define RFootCg_id 7
#define LHipmotCg_id 8
#define LThighUpLegCg_id 9
#define LThighLowLegCg_id 10
#define LLowLegCg_id 11
#define LFootmotCg_id 12
#define LFootCg_id 13
#define DWLCg_id 14
#define DWSCg_id 15
#define DWYCg_id 16
#define RShpCg_id 17
#define RShrCg_id 18
#define RShyCg_id 19
#define RElbCg_id 20
#define LShpCg_id 21
#define LShrCg_id 22
#define LShyCg_id 23
#define LElbCg_id 24


// extforce

#define Waist_contact_force_id 1
#define RThigh_contact_force_id 2
#define RLowLeg_contact_force_id 3
#define RFoot_Force_id 4
#define LThigh_contact_force_id 5
#define LLowLeg_contact_visu_id 6
#define LFoot_Force_id 7
#define Torso_contact_force_id 8
#define RShoulder_contact_force_id 9
#define RElbow_contact_force_id 10
#define LShoulder_contact_force_id 11
#define LElbow_contact_force_id 12


// links



// ============================================================ //

# endif
