/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Wed Apr 13 11:56:20 2016
 * --------------------------------------------------------
 *
 */
#ifndef USER_ALL_ID_h
#define USER_ALL_ID_h

// ============================================================ //


// joint

#define FJ_T1_Coman_id 1
#define FJ_T2_Coman_id 2
#define FJ_T3_Coman_id 3
#define FJ_R1_Coman_id 4
#define FJ_R2_Coman_id 5
#define FJ_R3_Coman_id 6
#define RHipSag_id 7
#define RHipLat_id 8
#define RHipYaw_id 9
#define RKneeSag_id 10
#define RAnkLat_id 11
#define RAnkSag_id 12
#define RToe_id 13
#define LHipSag_id 14
#define LHipLat_id 15
#define LHipYaw_id 16
#define LKneeSag_id 17
#define LAnkLat_id 18
#define LAnkSag_id 19
#define LToe_id 20
#define WaistLat_id 21
#define WaistSag_id 22
#define WaistYaw_id 23
#define RShSag_id 24
#define RShLat_id 25
#define RShYaw_id 26
#define RElb_id 27
#define LShSag_id 28
#define LShLat_id 29
#define LShYaw_id 30
#define LElb_id 31


// body

#define Waist_id 6
#define RHipmot_id 7
#define RThighUpLeg_id 8
#define RThighLowLeg_id 9
#define RLowLeg_id 10
#define RFootmot_id 11
#define RFoot_id 12
#define RFoot_distal_id 13
#define LHipmot_id 14
#define LThighUpLeg_id 15
#define LThighLowLeg_id 16
#define LLowLeg_id 17
#define LFootmot_id 18
#define LFoot_id 19
#define LFoot_distal_id 20
#define DWL_id 21
#define DWS_id 22
#define DWYTorso_id 23
#define RShp_id 24
#define RShr_id 25
#define RShy_id 26
#define RElb_id 27
#define LShp_id 28
#define LShr_id 29
#define LShy_id 30
#define LElb_id 31


// point

//#define origin_id 0
#define Point_Waist_1_id 1
#define Point_Waist_2_id 2
#define Point_Waist_3_id 3
#define Point_Waist_Cg_id 4
#define Point_RHipmot_id 5
#define Point_RHipmot_Cg_id 6
#define Point_RThighUpLeg_id 7
#define Point_RThighUpLeg_Cg_id 8
//#define origin_id 9
#define Point_RThighLowLeg_id 10
#define Point_RThighLowLeg_Cg_id 11
//#define origin_id 12
#define Point_RLowLeg_id 13
#define Point_RLowLeg_Cg_id 14
#define Point_RFootmot_id 15
#define Point_RFootmot_Cg_id 16
#define Point_RFoot_Cg_id 17
#define Point_RFoot_F_id 18
#define Point_RSpring_id 19
#define Point_RToe_F_id 20
#define Point_LHipmot_id 21
#define Point_LHipmot_Cg_id 22
#define Point_LThighUpLeg_id 23
#define Point_LThighUpLeg_Cg_id 24
//#define origin_id 25
#define Point_LThighLowLeg_id 26
#define Point_LThighLowLeg_Cg_id 27
//#define origin_id 28
#define Point_LLowLeg_id 29
#define Point_LLowLeg_Cg_id 30
#define Point_LFootmot_id 31
#define Point_LFootmot_Cg_id 32
#define Point_LFoot_Cg_id 33
#define Point_LFoot_F_id 34
#define Point_LSpring_id 35
#define Point_LToe_f_id 36
#define Point_DWL_id 37
#define Point_DWL_Cg_id 38
#define Point_DWS_id 39
#define Point_DWS_Cg_id 40
//#define origin_id 41
#define Point_DWYTorso_Cg_id 42
#define Point_DWYTorso_1_id 43
#define Point_DWYTorso_2_id 44
#define Point_RShp_Cg_id 45
#define Point_RShp_id 46
#define Point_RShr_Cg_id 47
#define Point_RShr_id 48
//#define origin_id 49
#define Point_RShy_Cg_id 50
#define Point_RShy_id 51
//#define origin_id 52
#define Point_RElb_Cg_id 53
#define Point_LShp_Cg_id 54
#define Point_LShp_id 55
#define Point_LShr_Cg_id 56
#define Point_LShr_id 57
//#define origin_id 58
#define Point_LShy_Cg_id 59
#define Point_LShy_id 60
//#define origin_id 61
#define Point_LElb_Cg_id 62


// sensor

#define WaistCg_id 1
#define RHipmotCg_id 2
#define RThighUpLegCg_id 3
#define RThighLowLegCg_id 4
#define RLowLegCg_id 5
#define RFootmotCg_id 6
#define RFootCg_id 7
#define LHipmotCg_id 8
#define LThighUpLegCg_id 9
#define LThighLowLegCg_id 10
#define LLowLegCg_id 11
#define LFootmotCg_id 12
#define LFootCg_id 13
#define DWLCg_id 14
#define DWSCg_id 15
#define DWYCg_id 16
#define RShpCg_id 17
#define RShrCg_id 18
#define RShyCg_id 19
#define RElbCg_id 20
#define LShpCg_id 21
#define LShrCg_id 22
#define LShyCg_id 23
#define LElbCg_id 24


// extforce

#define Waist_contact_force_id 1
#define RThigh_contact_force_id 2
#define RLowLeg_contact_force_id 3
#define RFoot_Force_id 4
#define RFoot_dist_force_id 5
#define LThigh_contact_force_id 6
#define LLowLeg_contact_visu_id 7
#define LFoot_Force_id 8
#define LFoot_dist_force_id 9
#define Torso_contact_force_id 10
#define RShoulder_contact_force_id 11
#define RElbow_contact_force_id 12
#define LShoulder_contact_force_id 13
#define LElbow_contact_force_id 14


// links



// ============================================================ //

# endif
