/* --------------------------------------------------------
 * This code interface mbs data struct with an arbitrary user model 
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Fri Apr 10 11:43:58 2015
 * --------------------------------------------------------
 *
 */
#ifndef MBS_USER_INTERFACE_h 
#define MBS_USER_INTERFACE_h

// ============================================================ //


typedef struct UserModel  UserModel;

#ifdef __cplusplus
extern "C" {
#endif
	UserModel* mbs_new_user_model();
	void mbs_delete_user_model(UserModel* ums);
#ifdef __cplusplus
}
#endif
// ============================================================ //

typedef struct UserIO UserIO;

#ifdef __cplusplus
extern "C" {
#endif
	UserIO * mbs_new_user_IO();
	void mbs_delete_user_IO(UserIO *uvs);
#ifdef __cplusplus
}
#endif
 
# endif
