/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Tue May 19 13:31:40 2015
 * --------------------------------------------------------
 *
 */
#ifndef USERMODEL_h
#define USERMODEL_h

#include "lut.h"

#include "mbs_user_interface.h"
// ============================================================ //

struct UserModel 
{
	void *cppInterface;
};

// ============================================================ //
 
# endif
