#!/bin/bash

echo "Extracting $*"
echo $'\n'

# loop on all the inputs
for var in "$@"
do
	# copy the result files (related to $var) from bioroblinux to the current directory (local computer)
	scp -r harding@bioroblinux.epfl.ch:/home/harding/BIOROB/opti_res/coman_matthew/workR/Optis/$var/results  ./$var

	echo "---> $var extracted"
	echo $'\n'
done
