#!/bin/bash

# create the 'Optis' folder
if [ -d "/home/harding/BIOROB/opti_res/coman_matthew/workR/" ]; then
	echo "'Optis' folder already created"
else
	mkdir /home/harding/BIOROB/opti_res/coman_matthew/workR

	echo "'Optis' folder created"
fi

# loop on all the inputs
for var in "$@"
do
	# create the folder $var inside the 'optis' folder
	mkdir /home/harding/BIOROB/opti_res/coman_matthew/workR/$var

	# go to the $var folder
	cd /home/harding/BIOROB/opti_res/coman_matthew/workR/$var

	# create the folder 'config_out' inside the $var folder
	mkdir /home/harding/BIOROB/opti_res/coman_matthew/workR/$var/config_out

	# create the folder 'results' inside the $var folder
	mkdir /home/harding/BIOROB/opti_res/coman_matthew/workR/$var/results

	# cmake
	cmake -D CMAKE_C_COMPILER=gcc-4.6 -D CMAKE_CXX_COMPILER=g++-4.6 /home/harding/BIOROB/opti_res/coman_matthew/workR >> config_out/cmake_out.txt

	echo "-------- CMake done for $var --------"
	echo $'\n'
done

# loop on all the inputs
for var in "$@"
do
	# launch the shell script 'runOptiScript' for $var
	screen -d -m -S $var /home/harding/BIOROB/opti_res/coman_matthew/opti/scripts/runOptiScript $var

	echo "---> Compilation launched for $var"
	echo $'\n'

	# wait 2 seconds (safety)
	sleep 2
done
